defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
      title: Monty Hall by bgbrandongomez
      project: Monty Hall
      projectid: MontyHall
      developer: bgbrandongomez
      branch: master
      site-branch: gh-pages
      description: A program that shows the probability of getting a car when switching Monty Hall's doors is 2/3, not 1/2.
      site-url: https://senorcontento.github.io
      project-url: https://bgbrandongomez.github.io
      date: 0000-00-00 00:00:00

markdown: kramdown
